package compte.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Depenses")
public class Depense {
	
	private String id;
	private double montant;
	private long date;
	private String categorie;
	
	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName="montant")  
	public double getMontant() {
		return montant;
	}
	public void setMontant(double montant) {
		this.montant = montant;
	}
	
	@DynamoDBAttribute(attributeName="datedepense")  
	public long getDate() {
		return date;
	}
	public void setDate(long date) {
		this.date = date;
	}
	
	@DynamoDBHashKey(attributeName="categorie")  
	public String getCategorie() {
		return categorie;
	}
	public void setCategorie(String idCategorie) {
		this.categorie = idCategorie;
	}
	
	
	public Depense() {
		super();
	}
	@Override
	public String toString() {
		return "Depense [id=" + id + ", montant=" + montant + ", date=" + date + ", categorie=" + categorie + "]";
	}
	
}
